### ISSUE TITLE
Raw Data Explorer does not display data for crawler li-entsg

### ISSUE THREAD

**Issue by brawer** [opensanctions/site#481]
The Raw Data Explorer currently does not display data for crawler `li-entsg`.

To reproduce, click on "Raw Data Explorer" at the bottom of [this page](https://www.opensanctions.org/entities/li-entsg-527eb6da1f6cf14a5a734c8141c66213f04fcb0a/). Expected: raw data on the [linked page](https://www.opensanctions.org/statements/?canonical_id=li-entsg-527eb6da1f6cf14a5a734c8141c66213f04fcb0a). Observed: no data is displayed.

For other data sources, however, it seems to work; [example](https://www.opensanctions.org/statements/?canonical_id=usgsa-s4mr3mvn2).

**Comment by pudo** [comment]
Yep, the statement API is running against a non-current dataset. Hoping to get the new API code deployed next week:)

**Comment by pudo** [comment]
Ups, this has been fixed for a couple of days now :)
